pool:
    vmImage: 'vs2017-win2016'
steps:
- task: NuGetInstaller@0
  displayName: 'NuGet restore'
  inputs:
    solution: GradingApp/GradingApp.sln
    verbosity: Detailed

- task: VSBuild@1
  displayName: 'Build solution GradingApp/GradingApp.sln'
  inputs:
    solution: GradingApp/GradingApp.sln
    vsVersion: 15.0
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)\\"'


- task: CopyFiles@2
  displayName: 'Copy ARM templates'
  inputs:
    SourceFolder: arm
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: dropWebApp'
  inputs:
    ArtifactName: dropWebApp

