steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'Create Azure App Service'
  inputs:
    azureSubscription: 'Visual Studio Enterprise(Converted to EA) (6d1eca2e-45dc-4dab-836a-49ee682dd37e)'
    resourceGroupName: victest01
    location: 'East US'
    csmFile: '$(System.DefaultWorkingDirectory)/dropWebApp/dropWebApp/azuredeploy.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/dropWebApp/dropWebApp/azuredeploy.parameters.json'
    overrideParameters: '-webAppName "labgradinggbac1"'
    deploymentOutputs: webAppUrl

    #Your build pipeline references an undefined variable named ‘webAppUrl’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- powershell: |
   # Write your powershell commands here.
   
   $url = ConvertFrom-Json '$(webAppUrl)'
   $url.url.value
   # Use the environment variables input below to pass secret variables to this script.
  displayName: 'Get Web App URL'


  variables:
  url: ''

steps:
- task: AzureRmWebAppDeployment@3
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: 'Visual Studio Enterprise(Converted to EA) (6d1eca2e-45dc-4dab-836a-49ee682dd37e)'
    appType: webApp
    WebAppName: '$(url)'
    Package: '$(System.DefaultWorkingDirectory)\**\*.zip'
    TakeAppOfflineFlag: true

